# Generated by Django 3.1.7 on 2021-03-23 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_admission', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Colleges_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=50)),
                ('college_address', models.CharField(max_length=100)),
                ('college_image', models.ImageField(upload_to='College_Images')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Course_Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_branch', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Degree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_degree', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_field', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_fee', models.IntegerField()),
                ('college_select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.colleges_model')),
                ('course_select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.course')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.course_branch'),
        ),
        migrations.AddField(
            model_name='course',
            name='colleges',
            field=models.ManyToManyField(to='colleges.Colleges_Model'),
        ),
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.course_degree'),
        ),
        migrations.AddField(
            model_name='course',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.course_field'),
        ),
    ]
