# Generated by Django 3.1.7 on 2021-05-05 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_course_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admission_Type',
        ),
        migrations.RemoveField(
            model_name='course',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='course',
            name='colleges',
        ),
        migrations.RemoveField(
            model_name='course',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='course',
            name='field',
        ),
        migrations.RemoveField(
            model_name='course_fee',
            name='college_select',
        ),
        migrations.RemoveField(
            model_name='course_fee',
            name='course_select',
        ),
        migrations.DeleteModel(
            name='Colleges_Model',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Course_Branch',
        ),
        migrations.DeleteModel(
            name='Course_Degree',
        ),
        migrations.DeleteModel(
            name='Course_Fee',
        ),
        migrations.DeleteModel(
            name='Course_Field',
        ),
    ]
